name: Automated Release

on:
  push:
    tags:
      - 'v*' # This triggers the action when any tag starting with 'v' is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
